### ISSUE TITLE
Orders & Revenue not passed along

### ISSUE THREAD

**Issue by guillaumecabane** [segment-integrations/integration-trakio#1]
Orders & Revenue are supported in Trak.io, but the mapper does not handle them http://docs.trak.io/properties.html 
![image](https://cloud.githubusercontent.com/assets/1849807/5893416/55d38ad8-a4e3-11e4-9dd8-9d5760654a8a.png)

**Comment by hankim813** [comment]
Added to JIRA https://segment.atlassian.net/browse/INT-214
